import type { CatCharacter } from './types';

export const CATS: CatCharacter[] = [
  {
    id: '1',
    name: 'FCKED',
    color: '#e85d04',
    accent: '#9d0208',
    portrait: '/cats/fcked-cat-1.png',
    visuals: {
      fur: '#e07a3a',
      muzzle: '#f4d0a8',
      headwear: 'cap',
      headwearColor: '#c1121f',
      outfit: 'hoodie',
      outfitColor: '#6b2737',
      hasSunglasses: true,
      boardColor: '#2b2b2b',
      wheelColor: '#f4d0a8',
    },
  },
  {
    id: '2',
    name: 'FCKED C@TZ',
    color: '#6b4c2a',
    accent: '#f9c74f',
    portrait: '/cats/fcked-cat-2.png',
    visuals: {
      fur: '#5c3d1e',
      muzzle: '#c4b5a5',
      headwear: 'beanie',
      headwearColor: '#2d6a4f',
      outfit: 'hoodie',
      outfitColor: '#f9c74f',
      hasSunglasses: false,
      boardColor: '#1d3557',
      wheelColor: '#f9c74f',
    },
  },
  {
    id: '3',
    name: 'Bandana',
    color: '#9ca3af',
    accent: '#4d7c0f',
    portrait: '/cats/fcked-cat-3.png',
    visuals: {
      fur: '#9ca3af',
      muzzle: '#e5e7eb',
      headwear: 'bandana',
      headwearColor: '#2563eb',
      outfit: 'jacket',
      outfitColor: '#4d7c0f',
      outfitAccent: '#a3a948',
      hasSunglasses: true,
      hasEarring: true,
      boardColor: '#374151',
      wheelColor: '#fbbf24',
    },
  },
];
